spring:
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

